export const PICK_SELECTED_MEDIA_TYPE = 'PICK_SELECTED_MEDIA_TYPE';

export const SEARCH = 'SEARCH';
export const FETCH_SEARCH = 'FETCH_SEARCH';
export const FETCH_SEARCH_START = 'FETCH_SEARCH_START';
export const FETCH_SEARCH_SUCCESS = 'FETCH_SEARCH_SUCCESS';
export const FETCH_SEARCH_FAIL = 'FETCH_SEARCH_FAIL';

export const FETCH_SELECTED_START = 'FETCH_SELECTED_START';
export const FETCH_SELECTED_SUCCESS = 'FETCH_SELECTED_SUCCESS';
export const FETCH_SELECTED_FAIL = 'FETCH_SELECTED_FAIL';

export const SHOW_SELECTED = 'SHOW_SELECTED';
export const HIDE_SELECTED = 'HIDE_SELECTED';

export const FETCH_FILTERED_RESULTS_START = 'FETCH_FILTERED_RESULTS_START';
export const FETCH_FILTERED_RESULTS_SUCCESS = 'FETCH_FILTERED_RESULTS_SUCCESS';
export const FETCH_FILTERED_RESULTS_FAIL = 'FETCH_FILTERED_RESULTS_FAIL';

// Auth actionTypes
export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

// Media actionTypes ADD MEDIA TO FIRESTORE COLLECTION
export const ADD_MEDIA_TO_FIRESTORE_START = 'ADD_MEDIA_TO_FIRESTORE_START';
export const ADD_MEDIA_TO_FIRESTORE_SUCCESS = 'ADD_MEDIA_TO_FIRESTORE_SUCCESS';
export const ADD_MEDIA_TO_FIRESTORE_FAIL = 'ADD_MEDIA_TO_FIRESTORE_FAIL';

// Media actionTypes Get Collections
export const GET_MEDIA_COLLECTIONS_START = 'GET_MEDIA_COLLECTIONS_START';
export const GET_MEDIA_COLLECTIONS_SUCCESS = 'GET_MEDIA_COLLECTIONS_SUCCESS';
export const GET_MEDIA_COLLECTIONS_FAIL = 'GET_MEDIA_COLLECTIONS_FAIL';

// Collection actionTypes
export const RENDER_COLLECTION_START = 'RENDER_COLLECTION_START';
export const RENDER_COLLECTION_SUCCESS = 'RENDER_COLLECTION_SUCCESS';
export const RENDER_COLLECTION_FAIL = 'RENDER_COLLECTION_FAIL';