export const PICK_SELECTED_MEDIA_TYPE = 'PICK_SELECTED_MEDIA_TYPE';

export const SEARCH = 'SEARCH';
export const FETCH_SEARCH = 'FETCH_SEARCH';
export const FETCH_SEARCH_START = 'FETCH_SEARCH_START';
export const FETCH_SEARCH_SUCCESS = 'FETCH_SEARCH_SUCCESS';
export const FETCH_SEARCH_FAIL = 'FETCH_SEARCH_FAIL';

export const FETCH_SELECTED_START = 'FETCH_SELECTED_START';
export const FETCH_SELECTED_SUCCESS = 'FETCH_SELECTED_SUCCESS';
export const FETCH_SELECTED_FAIL = 'FETCH_SELECTED_FAIL';

