name: Build and Deploy to Firebase [PRODUCTION]

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: PRODUCTION

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 10.20.0

    # Step 3: Install dependencies
    - name: Install dependencies
      run: npm install

    # Step 4: Inject .env variables
    - name: Create .env file
      run: |
        echo "SASS_PATH=${{ secrets.SASS_PATH }}" >> .env
        
        echo "REACT_APP_THE_MOVIE_DB_API_KEY=${{ secrets.REACT_APP_THE_MOVIE_DB_API_KEY }}" >> .env
        echo "REACT_APP_THE_MOVIE_DB_API_VERSION=${{ secrets.REACT_APP_THE_MOVIE_DB_API_VERSION }}" >> .env
        echo "REACT_APP_THE_MOVIE_DB_API_SEARCH=${{ secrets.REACT_APP_THE_MOVIE_DB_API_SEARCH }}" >> .env
        echo "REACT_APP_THE_MOVIE_DB_API_IMAGE=${{ secrets.REACT_APP_THE_MOVIE_DB_API_IMAGE }}" >> .env
        
        echo "REACT_APP_FIREBASE_API_KEY=${{ secrets.REACT_APP_FIREBASE_API_KEY }}" >> .env
        echo "REACT_APP_FIREBASE_AUTH_DOMAIN=${{ secrets.REACT_APP_FIREBASE_AUTH_DOMAIN }}" >> .env
        echo "REACT_APP_FIREBASE_DATABASE_URL=${{ secrets.REACT_APP_FIREBASE_DATABASE_URL }}" >> .env
        echo "REACT_APP_FIREBASE_PROJECT_ID=${{ secrets.REACT_APP_FIREBASE_PROJECT_ID }}" >> .env
        echo "REACT_APP_FIREBASE_STORAGE_BUCKET=${{ secrets.REACT_APP_FIREBASE_STORAGE_BUCKET }}" >> .env
        echo "REACT_APP_FIREBASE_MESSAGING_SENDER_ID=${{ secrets.REACT_APP_FIREBASE_MESSAGING_SENDER_ID }}" >> .env
        echo "REACT_APP_FIREBASE_API_ID=${{ secrets.REACT_APP_FIREBASE_API_ID }}" >> .env
        echo "REACT_APP_FIREBASE_MEASUREMENT_ID=${{ secrets.REACT_APP_FIREBASE_MEASUREMENT_ID }}" >> .env

    # Step 5: Build the React app
    - name: Build the app
      run: npm run build

    # Step 6: Deploy to Firebase
    - name: Deploy to Firebase
      uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: ${{ secrets.GITHUB_TOKEN }}
        firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        channelId: live
